In [2]:
import numpy as np
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.kernel_approximation import RBFSampler
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC
from sklearn import svm

In [3]:
dataset=np.loadtxt("train.csv",delimiter=",") #i removed the labels so i can read it as text file
#But if u want to read it as it is import pandas and read csv

In [4]:
train_label=dataset[:,0] #collecting labels

In [5]:
np.shape(train_label) #checking the size 

(42000,)

In [6]:
np.shape(dataset)

(42000, 785)

In [7]:
train_label

array([1., 0., 1., ..., 7., 6., 9.])

In [8]:
train_data=dataset[:,1:785]

In [9]:
np.shape(train_data)

(42000, 784)

In [10]:
traind,testd,trainl,testl=train_test_split(train_data,train_label,test_size=0.25,random_state=10)

In [11]:
model = RandomForestClassifier(n_estimators=100)
model = model.fit(traind, trainl)

# make predictions
expected = testl
predicted = model.predict(testd)
y_train1 = expected
y_pred = predicted
accuracy = accuracy_score(y_train1, y_pred)


print("accuracy")
print("%.3f" %accuracy)


accuracy
0.963


In [29]:
expected

array([7., 3., 9., ..., 2., 6., 4.])

In [30]:
dataset=np.loadtxt("test1.csv",delimiter=",")

In [31]:
k=model.predict(dataset)

In [39]:
np.rint(k)

array([2., 0., 9., ..., 3., 9., 2.])

In [40]:
np.savetxt("out.csv",k)